language: node_js
node_js: "14.14"

_npx-job: &npx-job
  language: node_js
  node_js: 14.14
  install: skip
  env: [ENVIRONMENT=production]

stages:
  - name: test

  - name: build
    if: tag =~ /^v\d+\.\d+\.\d+$/

  - name: production-started
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-finished
    if: tag =~ /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: test
      name: Test app

    - stage: build
      name: Build app
      install: skip
      script: scripts/build-image.sh leads-graph

    - <<: *npx-job
      stage: production-started
      name: Deployment Started
      script: npx @base-cms/website-deployment-tool notify-started

    - <<: *npx-job
      stage: production
      name: GraphQL Service
      script: npx @endeavorb2b/rancher2cli deploy l0-service leads-graph 300927244991.dkr.ecr.us-east-1.amazonaws.com/leads-graph:$TRAVIS_TAG

    - <<: *npx-job
      stage: production-finished
      name: Deployment Finished
      script: npx @base-cms/website-deployment-tool notify-finished
