# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ main ]

jobs:
  manage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - uses: actions/cache@v2
      working-directory: manage
      id: yarn-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('manage/yarn.lock') }}

    - name: Install dependencies
      working-directory: manage
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

    - name: Run tests
      working-directory: manage
      run: yarn test

  monorepo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - uses: actions/cache@v2
      working-directory: monorepo
      id: yarn-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('monorepo/yarn.lock') }}

    - name: Install dependencies
      working-directory: monorepo
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

    - name: Run tests
      working-directory: monorepo
      run: yarn test
